### ISSUE TITLE
How to reproduce the coverage test？

### ISSUE THREAD

**Issue by duerwuyi** [LGU-SE-Internal/GRev#61]
How to reproduce the coverage test of Figure 7: 24-Hours Code Coverages Comparison？
Thx.

**Comment by joyemang33** [comment]
Sorry for late response, you may try to use this script to reproduce the expriments of coverage comparison (for example, redis): https://github.com/CUHK-SE-Group/GRev/blob/main/reproduce/reids_cov.sh

Please feel free to tell us if you have further questions.

Best regards,
Qiuyang
